baseurl = "https://www.effinger.ch/"
languageCode = "de"
title = "Effinger — Kaffeebar & Coworking Space Bern"
pluralizeListTitles = false
preserveTaxonomyNames = true
removePathAccents = true
enableRobotsTXT = true
paginatePath = "seite"

disableFastRender = true

[params]
  author = "Coworking Community Bern"
  analyticsId = "UA-56906982-1"
  disqusShortname = "effinger"

[taxonomies]
  category = "categories"  # Used for events
  finanzen = "finanzen"

[permalinks]
  blog-tag = "/blog/tag/:title/"

[[menu.main]]
  name = "Community"
  pre = "<i class='fa fa-users'></i>"
  weight = 3
  url = "/community/"
